restart_file: CANN-2024-01-29-test_runS3.nc
start_datetime: 2024-01-28 00:00:00
forecast_start_datetime: 2024-01-30 00:00:00
end_datetime: .na.character
forecast_horizon: 16
sim_name: test_runS3
configure_flare: configure_flare.yml
configure_obs: observation_processing.yml
use_s3: no
