restart_file: .na
start_datetime: 2023-11-01 00:00:00
end_datetime: .na
forecast_start_datetime: 2024-02-01 00:00:00
forecast_horizon: 30
sim_name: testing
configure_flare: configure_flare.yml
configure_obs: observation_processing.yml
use_s3: false
