restart_file: .na
start_datetime: 2022-10-25 00:00:00
end_datetime: .na
forecast_start_datetime: 2022-11-10 00:00:00
forecast_horizon: 16.0
sim_name: test_runS3
configure_flare: configure_flare.yml
configure_obs: observation_processing.yml
use_s3: true
