on:
  workflow_dispatch:
  # schedule:
  # - cron: "0 11 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rqthomas/flare-rocker:4.4
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

# Point to the right path, run the right Rscript command
      - name: Run automatic prediction file
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SC_AWS_KEY: ${{ secrets.SC_AWS_KEY }}
          SC_AWS_SECRET: ${{ secrets.SC_AWS_SECRET }}
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run:  Rscript $GITHUB_WORKSPACE/workflows/glm_flare_v3/forecast_workflow.R
