on:
  workflow_dispatch:
  schedule:
  - cron: "0 11 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rqthomas/flare-rocker:4.3.2
    steps:
      - name: Checkout repo
        uses: actions/checkout@4
        with:
          fetch-depth: 0
          
      - name: install deps
        shell: Rscript {0}
        run: |
          install.packages('tidymodels')
          install.packages('xgboost')
          install.packages('RcppRoll')

# Point to the right path, run the right Rscript command
      - name: Run automatic prediction file
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SC_AWS_KEY: ${{ secrets.SC_AWS_KEY }}
          SC_AWS_SECRET: ${{ secrets.SC_AWS_SECRET }}
        run:  Rscript $GITHUB_WORKSPACE/workflows/default/combined_workflow.R
